// Code generated by ent, DO NOT EDIT.

package ent

import (
	"errors"
	"fmt"

	"github.com/woocoos/kocli/integration/resource/ent/predicate"
	"github.com/woocoos/kocli/integration/resource/ent/resource"
)

// ResourceWhereInput represents a where input for filtering Resource queries.
type ResourceWhereInput struct {
	Predicates []predicate.Resource  `json:"-"`
	Not        *ResourceWhereInput   `json:"not,omitempty"`
	Or         []*ResourceWhereInput `json:"or,omitempty"`
	And        []*ResourceWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *int  `json:"id,omitempty"`
	IDNEQ   *int  `json:"idNEQ,omitempty"`
	IDIn    []int `json:"idIn,omitempty"`
	IDNotIn []int `json:"idNotIn,omitempty"`
	IDGT    *int  `json:"idGT,omitempty"`
	IDGTE   *int  `json:"idGTE,omitempty"`
	IDLT    *int  `json:"idLT,omitempty"`
	IDLTE   *int  `json:"idLTE,omitempty"`

	// "name" field predicates.
	Name             *string  `json:"name,omitempty"`
	NameNEQ          *string  `json:"nameNEQ,omitempty"`
	NameIn           []string `json:"nameIn,omitempty"`
	NameNotIn        []string `json:"nameNotIn,omitempty"`
	NameGT           *string  `json:"nameGT,omitempty"`
	NameGTE          *string  `json:"nameGTE,omitempty"`
	NameLT           *string  `json:"nameLT,omitempty"`
	NameLTE          *string  `json:"nameLTE,omitempty"`
	NameContains     *string  `json:"nameContains,omitempty"`
	NameHasPrefix    *string  `json:"nameHasPrefix,omitempty"`
	NameHasSuffix    *string  `json:"nameHasSuffix,omitempty"`
	NameEqualFold    *string  `json:"nameEqualFold,omitempty"`
	NameContainsFold *string  `json:"nameContainsFold,omitempty"`

	// "description" field predicates.
	Description             *string  `json:"description,omitempty"`
	DescriptionNEQ          *string  `json:"descriptionNEQ,omitempty"`
	DescriptionIn           []string `json:"descriptionIn,omitempty"`
	DescriptionNotIn        []string `json:"descriptionNotIn,omitempty"`
	DescriptionGT           *string  `json:"descriptionGT,omitempty"`
	DescriptionGTE          *string  `json:"descriptionGTE,omitempty"`
	DescriptionLT           *string  `json:"descriptionLT,omitempty"`
	DescriptionLTE          *string  `json:"descriptionLTE,omitempty"`
	DescriptionContains     *string  `json:"descriptionContains,omitempty"`
	DescriptionHasPrefix    *string  `json:"descriptionHasPrefix,omitempty"`
	DescriptionHasSuffix    *string  `json:"descriptionHasSuffix,omitempty"`
	DescriptionIsNil        bool     `json:"descriptionIsNil,omitempty"`
	DescriptionNotNil       bool     `json:"descriptionNotNil,omitempty"`
	DescriptionEqualFold    *string  `json:"descriptionEqualFold,omitempty"`
	DescriptionContainsFold *string  `json:"descriptionContainsFold,omitempty"`

	// "tenant_id" field predicates.
	TenantID             *string  `json:"tenantID,omitempty"`
	TenantIDNEQ          *string  `json:"tenantIDNEQ,omitempty"`
	TenantIDIn           []string `json:"tenantIDIn,omitempty"`
	TenantIDNotIn        []string `json:"tenantIDNotIn,omitempty"`
	TenantIDGT           *string  `json:"tenantIDGT,omitempty"`
	TenantIDGTE          *string  `json:"tenantIDGTE,omitempty"`
	TenantIDLT           *string  `json:"tenantIDLT,omitempty"`
	TenantIDLTE          *string  `json:"tenantIDLTE,omitempty"`
	TenantIDContains     *string  `json:"tenantIDContains,omitempty"`
	TenantIDHasPrefix    *string  `json:"tenantIDHasPrefix,omitempty"`
	TenantIDHasSuffix    *string  `json:"tenantIDHasSuffix,omitempty"`
	TenantIDIsNil        bool     `json:"tenantIDIsNil,omitempty"`
	TenantIDNotNil       bool     `json:"tenantIDNotNil,omitempty"`
	TenantIDEqualFold    *string  `json:"tenantIDEqualFold,omitempty"`
	TenantIDContainsFold *string  `json:"tenantIDContainsFold,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *ResourceWhereInput) AddPredicates(predicates ...predicate.Resource) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the ResourceWhereInput filter on the ResourceQuery builder.
func (i *ResourceWhereInput) Filter(q *ResourceQuery) (*ResourceQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyResourceWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyResourceWhereInput is returned in case the ResourceWhereInput is empty.
var ErrEmptyResourceWhereInput = errors.New("ent: empty predicate ResourceWhereInput")

// P returns a predicate for filtering resources.
// An error is returned if the input is empty or invalid.
func (i *ResourceWhereInput) P() (predicate.Resource, error) {
	var predicates []predicate.Resource
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, resource.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.Resource, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, resource.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.Resource, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, resource.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, resource.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, resource.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, resource.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, resource.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, resource.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, resource.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, resource.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, resource.IDLTE(*i.IDLTE))
	}
	if i.Name != nil {
		predicates = append(predicates, resource.NameEQ(*i.Name))
	}
	if i.NameNEQ != nil {
		predicates = append(predicates, resource.NameNEQ(*i.NameNEQ))
	}
	if len(i.NameIn) > 0 {
		predicates = append(predicates, resource.NameIn(i.NameIn...))
	}
	if len(i.NameNotIn) > 0 {
		predicates = append(predicates, resource.NameNotIn(i.NameNotIn...))
	}
	if i.NameGT != nil {
		predicates = append(predicates, resource.NameGT(*i.NameGT))
	}
	if i.NameGTE != nil {
		predicates = append(predicates, resource.NameGTE(*i.NameGTE))
	}
	if i.NameLT != nil {
		predicates = append(predicates, resource.NameLT(*i.NameLT))
	}
	if i.NameLTE != nil {
		predicates = append(predicates, resource.NameLTE(*i.NameLTE))
	}
	if i.NameContains != nil {
		predicates = append(predicates, resource.NameContains(*i.NameContains))
	}
	if i.NameHasPrefix != nil {
		predicates = append(predicates, resource.NameHasPrefix(*i.NameHasPrefix))
	}
	if i.NameHasSuffix != nil {
		predicates = append(predicates, resource.NameHasSuffix(*i.NameHasSuffix))
	}
	if i.NameEqualFold != nil {
		predicates = append(predicates, resource.NameEqualFold(*i.NameEqualFold))
	}
	if i.NameContainsFold != nil {
		predicates = append(predicates, resource.NameContainsFold(*i.NameContainsFold))
	}
	if i.Description != nil {
		predicates = append(predicates, resource.DescriptionEQ(*i.Description))
	}
	if i.DescriptionNEQ != nil {
		predicates = append(predicates, resource.DescriptionNEQ(*i.DescriptionNEQ))
	}
	if len(i.DescriptionIn) > 0 {
		predicates = append(predicates, resource.DescriptionIn(i.DescriptionIn...))
	}
	if len(i.DescriptionNotIn) > 0 {
		predicates = append(predicates, resource.DescriptionNotIn(i.DescriptionNotIn...))
	}
	if i.DescriptionGT != nil {
		predicates = append(predicates, resource.DescriptionGT(*i.DescriptionGT))
	}
	if i.DescriptionGTE != nil {
		predicates = append(predicates, resource.DescriptionGTE(*i.DescriptionGTE))
	}
	if i.DescriptionLT != nil {
		predicates = append(predicates, resource.DescriptionLT(*i.DescriptionLT))
	}
	if i.DescriptionLTE != nil {
		predicates = append(predicates, resource.DescriptionLTE(*i.DescriptionLTE))
	}
	if i.DescriptionContains != nil {
		predicates = append(predicates, resource.DescriptionContains(*i.DescriptionContains))
	}
	if i.DescriptionHasPrefix != nil {
		predicates = append(predicates, resource.DescriptionHasPrefix(*i.DescriptionHasPrefix))
	}
	if i.DescriptionHasSuffix != nil {
		predicates = append(predicates, resource.DescriptionHasSuffix(*i.DescriptionHasSuffix))
	}
	if i.DescriptionIsNil {
		predicates = append(predicates, resource.DescriptionIsNil())
	}
	if i.DescriptionNotNil {
		predicates = append(predicates, resource.DescriptionNotNil())
	}
	if i.DescriptionEqualFold != nil {
		predicates = append(predicates, resource.DescriptionEqualFold(*i.DescriptionEqualFold))
	}
	if i.DescriptionContainsFold != nil {
		predicates = append(predicates, resource.DescriptionContainsFold(*i.DescriptionContainsFold))
	}
	if i.TenantID != nil {
		predicates = append(predicates, resource.TenantIDEQ(*i.TenantID))
	}
	if i.TenantIDNEQ != nil {
		predicates = append(predicates, resource.TenantIDNEQ(*i.TenantIDNEQ))
	}
	if len(i.TenantIDIn) > 0 {
		predicates = append(predicates, resource.TenantIDIn(i.TenantIDIn...))
	}
	if len(i.TenantIDNotIn) > 0 {
		predicates = append(predicates, resource.TenantIDNotIn(i.TenantIDNotIn...))
	}
	if i.TenantIDGT != nil {
		predicates = append(predicates, resource.TenantIDGT(*i.TenantIDGT))
	}
	if i.TenantIDGTE != nil {
		predicates = append(predicates, resource.TenantIDGTE(*i.TenantIDGTE))
	}
	if i.TenantIDLT != nil {
		predicates = append(predicates, resource.TenantIDLT(*i.TenantIDLT))
	}
	if i.TenantIDLTE != nil {
		predicates = append(predicates, resource.TenantIDLTE(*i.TenantIDLTE))
	}
	if i.TenantIDContains != nil {
		predicates = append(predicates, resource.TenantIDContains(*i.TenantIDContains))
	}
	if i.TenantIDHasPrefix != nil {
		predicates = append(predicates, resource.TenantIDHasPrefix(*i.TenantIDHasPrefix))
	}
	if i.TenantIDHasSuffix != nil {
		predicates = append(predicates, resource.TenantIDHasSuffix(*i.TenantIDHasSuffix))
	}
	if i.TenantIDIsNil {
		predicates = append(predicates, resource.TenantIDIsNil())
	}
	if i.TenantIDNotNil {
		predicates = append(predicates, resource.TenantIDNotNil())
	}
	if i.TenantIDEqualFold != nil {
		predicates = append(predicates, resource.TenantIDEqualFold(*i.TenantIDEqualFold))
	}
	if i.TenantIDContainsFold != nil {
		predicates = append(predicates, resource.TenantIDContainsFold(*i.TenantIDContainsFold))
	}

	switch len(predicates) {
	case 0:
		return nil, ErrEmptyResourceWhereInput
	case 1:
		return predicates[0], nil
	default:
		return resource.And(predicates...), nil
	}
}
